# /docker-compose.yml

# =======================================================================================================
# --- Definição dos Serviços ---                                                                    #####
# =======================================================================================================
services:
  # =======================================================================================================
  # --- Serviço do Banco de Dados (PostgreSQL) ---                                                  #####
  # =======================================================================================================
  db:
    image: postgres:15-alpine
    container_name: crud_template_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mvp_user}       
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mvp_password} 
      POSTGRES_DB: ${POSTGRES_DB:-mvp_db}           
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mvp_user} -d ${POSTGRES_DB:-mvp_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # =======================================================================================================
  # --- Serviço do Backend (FastAPI) ---                                                              #####
  # =======================================================================================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crud_template_backend
    env_file:
      - ./backend/.env 
    ports:
      - "${BACKEND_PORT:-8000}:8000" 
    depends_on:
      db:
        condition: service_healthy 
    command: /app/entrypoint.sh
    restart: unless-stopped

  # =======================================================================================================
  # --- Serviço do Frontend (Vue.js com Vite) ---                                                   #####
  # =======================================================================================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crud_template_frontend
    ports:
      - "${FRONTEND_PORT:-5173}:5173" 
    environment:
      - VITE_API_BASE_URL=http://localhost:${BACKEND_PORT:-8000}${API_V1_STR:-/api/v1}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend 
    restart: unless-stopped

# =======================================================================================================
# --- Definição de Volumes ---                                                                      #####
# =======================================================================================================
volumes:
  postgres_data: 
    driver: local
